server:
  port: 8080
  servlet:
    session:
      timeout: 60m

spring:

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  datasource:
    url: jdbc:sqlserver://192.168.2.50:1433;databaseName=VocTrain;trustServerCertificate=false;encrypt=false;encrypth=false;sendStringParametersAsUnicode=false
    username: testUser
    password: ABCDabcd_123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/liquibase/db.changelog-master.yaml