--liquibase formatted sql

--changeset includeAll:create_table_vocabulary
CREATE TABLE dbo.vocabulary
(
    vocabulary_id       int identity (1,1)  PRIMARY KEY,
    word                Varchar(100)           NOT NULL,
    language_name       Varchar(20)            NOT NULL,
    part_of_speech      Varchar(20)                    ,
    translation_word    Varchar(100)           NOT NULL,
    localization_id     int                    NOT NULL,
    CONSTRAINT FK_vocabulary_localization FOREIGN KEY (localization_id)   REFERENCES localization (localization_id)
);

CREATE UNIQUE NONCLUSTERED INDEX NonClusteredIndex_vocabulary ON vocabulary (word,language_name);


INSERT INTO vocabulary (word, language_name, part_of_speech, translation_word, localization_id)
VALUES
  ('school', '中文', 'noun', '培训基地', 1),
  ('bye', '中文', 'exclamation', '再见', 1),
  ('hello', '中文', 'exclamation', '你好(用于打招呼)', 1),
  ('she', '中文', 'pronoun', '她', 1),
  ('three', '中文', 'number', '数字3', 1),
  ('twelve', '中文', 'number', '数字12', 1),
  ('twenty', '中文', 'number', '数字20', 1),
  ('two', '中文', 'number', '数字2', 1),
  ('what', '中文', 'pronoun', '什么,怎么', 1),
  ('your', '中文', 'determiner', '你的,你们的', 1),
  ('zero', '中文', 'number', '数字零(0)', 1),
  ('fifteen', '中文', 'number', '数字15', 1),
  ('fine', '中文', 'adjective', '身体好的', 1),
  ('five', '中文', 'number', '数字5', 1),
  ('four', '中文', 'number', '数字4', 1),
  ('fourteen', '中文', 'number', '数字14', 1),
  ('hi', '中文', 'exclamation', '你好', 1),
  ('how', '中文', 'adverb', '怎么样,如何', 1),
  ('meet', '中文', 'verb', '(初次)认识,会见', 1),
  ('my', '中文', 'determiner', '我的', 1),
  ('name', '中文', 'noun', '名字,姓名,名称', 1),
  ('nice', '中文', 'adjective', '吸引人的,美好的,令人愉快的', 1),
  ('nine', '中文', 'number', '数字9', 1),
  ('nineteen', '中文', 'number', '数字19', 1),
  ('number', '中文', 'noun', '数,数字', 1),
  ('one', '中文', 'number', '数字1', 1),
  ('seven', '中文', 'number', '数字7', 1),
  ('seventeen', '中文', 'number', '数字17', 1),
  ('six', '中文', 'number', '数字6', 1),
  ('sixteen', '中文', 'number', '数字16', 1),
  ('spell', '中文', 'verb', '拼写', 1),
  ('ten', '中文', 'number', '数字10', 1),
  ('thanks', '中文', 'exclamation', '多谢,谢谢', 1),
  ('that', '中文', 'determiner', '那,那个', 1),
  ('thirteen', '中文', 'number', '数字13', 1),
  ('this', '中文', 'determiner', '这,这个,这里', 1),
  ('phone', '中文', 'noun', '电话', 1),
  ('telephone', '中文', 'noun', '电话', 1),
  ('they', '中文', 'pronoun', '他们,它们', 1),
  ('you', '中文', 'pronoun', '你,你们', 1),
  ('student', '中文', 'noun', '学生', 1),
  ('eight', '中文', 'number', '数字8', 1),
  ('eighteen', '中文', 'number', '数字18', 1),
  ('eleven', '中文', 'number', '数字11', 1),
  ('his', '中文', 'determiner', '他的(所有格)', 2),
  ('cute', '中文', 'adjective', '可爱的,漂亮的', 2),
  ('black', '中文', 'adjective', '黑色的', 2),
  ('button', '中文', 'noun', '纽扣,按钮', 2),
  ('chair', '中文', 'noun', '椅子', 2),
  ('close', '中文', 'verb', '合上,收起', 2),
  ('earphones', '中文', 'noun', '耳机', 2),
  ('eighty', '中文', 'number', '数字80', 2),
  ('fifty', '中文', 'number', '数字50', 2),
  ('forty', '中文', 'number', '数字40', 2),
  ('green', '中文', 'adjective', '绿的,绿色的', 2),
  ('keyboard', '中文', 'noun', '(打字机,电脑等的)键盘', 2),
  ('listen', '中文', 'verb', '听,留神听', 2),
  ('microphone', '中文', 'noun', '话筒', 2),
  ('mouse', '中文', 'noun', '老鼠,鼠标', 2),
  ('ninety', '中文', 'number', '数字90', 2),
  ('open', '中文', 'verb', '打开(门,窗等)', 2),
  ('orange', '中文', 'adjective', '橙色的,橘黄色的', 2),
  ('pencil', '中文', 'noun', '铅笔', 2),
  ('pink', '中文', 'adjective', '粉红色的,淡红色的', 2),
  ('purple', '中文', 'adjective', '紫色的', 2),
  ('read', '中文', 'verb', '阅读,读书(能力)', 2),
  ('red', '中文', 'adjective', '红色的', 2),
  ('say', '中文', 'verb', '说', 2),
  ('screen', '中文', 'noun', '屏幕', 2),
  ('seventy', '中文', 'number', '数字70', 2),
  ('sixty', '中文', 'number', '数字60', 2),
  ('table', '中文', 'noun', '桌子', 2),
  ('thirty', '中文', 'number', '数字30', 2),
  ('white', '中文', 'adjective', '白色的', 2),
  ('write', '中文', 'verb', '写,写字,书写', 2),
  ('yellow', '中文', 'adjective', '黄色的', 2),
  ('computer', '中文', 'noun', '电脑', 2),
  ('notebook', '中文', 'noun', '笔记本', 2),
  ('kitchen', '中文', 'noun', '厨房', 2),
  ('window', '中文', 'noun', '窗户,视窗,窗口,橱窗', 2),
  ('blue', '中文', 'adjective', '天蓝色的', 2),
  ('book', '中文', 'noun', '书,书籍', 2),
  ('box', '中文', 'noun', '箱子,盒子', 2),
  ('pen', '中文', 'noun', '钢笔', 2),
  ('headphones', '中文', 'noun', '头戴耳机', 2),
  ('desk', '中文', 'noun', '办公桌,书桌', 2),
  ('elevator', '中文', 'noun', '电梯', 2),
  ('be', '中文', 'verb', '存在', 3),
  ('from', '中文', 'preposition', '从 ...... , 自…', 3),
  ('he', '中文', 'pronoun', '他(代词)', 3),
  ('her', '中文', 'determiner', '她的', 3),
  ('United States (of America)', '中文', 'noun', '美国,美利坚合众国', 3),
  ('country', '中文', 'noun', '国家', 3),
  ('French', '中文', 'adjective', '法国的,法国人的,法语的', 3),
  ('American', '中文', 'adjective', '美洲的;(尤指)美国的', 3),
  ('city', '中文', 'noun', '城市', 3),
  ('exciting', '中文', 'adjective', '令人兴奋的', 3),
  ('park', '中文', 'noun', '公园', 3),
  ('restaurant', '中文', 'noun', '餐馆,餐厅', 3),
  ('I', '中文', 'pronoun', '我', 3),
  ('it', '中文', 'pronoun', '它(代词)', 3),
  ('like', '中文', 'verb', '喜欢', 3),
  ('live', '中文', 'verb', '住,居住', 3),
  ('our', '中文', 'determiner', '我们的', 3),
  ('their', '中文', 'determiner', '他们的', 3),
  ('UK', '中文', 'abbreviation', '英国', 3),
  ('US', '中文', 'abbreviation', '美国,美国的', 3),
  ('we', '中文', 'pronoun', '我们', 3),
  ('where', '中文', 'adverb', '在哪里,到哪里,在 ... 位置', 3),
  ('Australian', '中文', 'adjective', '澳大利亚的', 3),
  ('British', '中文', 'adjective', '英国的', 3),
  ('crowded', '中文', 'adjective', '拥挤的', 3),
  ('boring', '中文', 'adjective', '令人厌烦的,无聊的', 3),
  ('building', '中文', 'noun', '建筑,建筑物', 3),
  ('shop', '中文', 'noun', '商店', 3),
  ('museum', '中文', 'noun', '博物馆,展览馆', 3),
  ('eye', '中文', 'noun', '眼睛,眼珠', 4),
  ('head', '中文', 'noun', '头部', 4),
  ('mouth', '中文', 'noun', '嘴巴', 4),
  ('nose', '中文', 'noun', '鼻子', 4),
  ('unhappy', '中文', 'adjective', '不快乐的,不高兴的,不幸福的,不满的', 4),
  ('architect', '中文', 'noun', '建筑师', 4),
  ('doctor', '中文', 'noun', '医生', 4),
  ('engineer', '中文', 'noun', '工程师', 4),
  ('husband', '中文', 'noun', '丈夫', 4),
  ('manager', '中文', 'noun', '主管,经理,负责人', 4),
  ('artist', '中文', 'noun', '艺术家', 4),
  ('clothes', '中文', 'noun', '衣服', 4),
  ('firefighter', '中文', 'noun', '消防队员', 4),
  ('aunt', '中文', 'noun', '阿姨,婶婶', 4),
  ('big', '中文', 'adjective', '(体积)大,(量)大,(程度)深', 4),
  ('brother', '中文', 'noun', '兄弟', 4),
  ('businessman', '中文', 'noun', '商人', 4),
  ('daughter', '中文', 'noun', '女儿', 4),
  ('family', '中文', 'noun', '家庭', 4),
  ('father', '中文', 'noun', '父亲', 4),
  ('female', '中文', 'adjective', '女性的', 4),
  ('grandparent', '中文', 'noun', '爷爷奶奶,外公外婆', 4),
  ('have', '中文', 'verb', '拥有', 4),
  ('male', '中文', 'adjective', '男性的,男子的,雄的,公的', 4),
  ('only child', '中文', 'noun', '独子,独女', 4),
  ('people', '中文', 'noun', '人,人类,人民', 4),
  ('sister', '中文', 'noun', '姐妹', 4),
  ('small', '中文', 'adjective', '(尺寸等)小的', 4),
  ('son', '中文', 'noun', '儿子,孩子', 4),
  ('uncle', '中文', 'noun', '伯父,姨丈,叔父,舅舅', 4),
  ('mother', '中文', 'noun', '母亲,妈妈', 4),
  ('teacher', '中文', 'noun', '教师,老师', 4),
  ('wife', '中文', 'noun', '妻子,太太', 4),
  ('brown', '中文', 'adjective', '棕色的,褐色的', 4),
  ('grandfather', '中文', 'noun', '爷爷,外公', 4),
  ('grandmother', '中文', 'noun', '奶奶,外婆', 4),
  ('face', '中文', 'noun', '脸,脸庞', 4),
  ('smile', '中文', 'noun', '微笑,笑容', 4),
  ('dress', '中文', 'noun', '裙子,连衣裙', 5),
  ('jacket', '中文', 'noun', '短上衣,夹克', 5),
  ('jeans', '中文', 'noun', '牛仔裤,粗斜纹棉布裤,工装裤', 5),
  ('pants', '中文', 'noun', '裤子', 5),
  ('shirt', '中文', 'noun', '衬衫', 5),
  ('baby', '中文', 'noun', '婴儿', 5),
  ('sweater', '中文', 'noun', '毛衣,毛绒衫,运动衫', 5),
  ('cheap', '中文', 'adjective', '便宜的', 5),
  ('want', '中文', 'verb', '需要,想要,希望', 5),
  ('work', '中文', 'verb', '工作,做工作,从事体力劳动或脑力劳动', 5),
  ('zip code', '中文', 'noun', '邮码,邮政区码', 5),
  ('shoe', '中文', 'noun', '鞋子', 5),
  ('skirt', '中文', 'noun', '裙子', 5),
  ('sock', '中文', 'noun', '短袜,袜子', 5),
  ('T-shirt', '中文', 'noun', '短袖圆领衫', 5),
  ('go', '中文', 'verb', '走', 5),
  ('cotton', '中文', 'noun', '棉花', 5),
  ('actor', '中文', 'noun', '男演员', 5),
  ('address', '中文', 'noun', '地址', 5),
  ('boss', '中文', 'noun', '老板,领导', 5),
  ('business card', '中文', 'noun', '名片', 5),
  ('drive', '中文', 'verb', '驾驶,开车', 5),
  ('email', '中文', 'noun', '电子邮件', 5),
  ('hospital', '中文', 'noun', '医院', 5),
  ('interesting', '中文', 'adjective', '有趣的,引人关注的', 5),
  ('nurse', '中文', 'noun', '护士,保姆', 5),
  ('office', '中文', 'noun', '办公室', 5),
  ('police officer', '中文', 'noun', '警官', 5),
  ('really', '中文', 'adverb', '真实地,真正地,实际上', 5),
  ('salary', '中文', 'noun', '薪水,工资,报酬', 5),
  ('secretary', '中文', 'noun', '秘书', 5),
  ('teach', '中文', 'verb', '教,教授', 5),
  ('theater', '中文', 'noun', '剧院,剧场', 5),
  ('waiter', '中文', 'noun', '服务员,侍者', 5),
  ('waitress', '中文', 'noun', '女服务生', 5),
  ('dollar', '中文', 'noun', '美元', 5),
  ('first', '中文', 'determiner', '第一', 5),
  ('home', '中文', 'noun', '家', 5),
  ('second', '中文', 'determiner', '第二的', 5),
  ('third', '中文', 'ordinal number', '第三', 5),
  ('woman', '中文', 'noun', '女人,妇女,女性', 5),
  ('banana', '中文', 'noun', '香蕉', 6),
  ('carrot', '中文', 'noun', '胡萝卜', 6),
  ('egg', '中文', 'noun', '蛋,卵', 6),
  ('fish', '中文', 'noun', '鱼', 6),
  ('fruit', '中文', 'noun', '水果', 6),
  ('knife', '中文', 'noun', '刀,小刀,菜刀,手术刀,匕首', 6),
  ('meat', '中文', 'noun', '肉', 6),
  ('noodle', '中文', 'noun', '面条', 6),
  ('vegetable', '中文', 'noun', '蔬菜,植物', 6),
  ('awful', '中文', 'adjective', '可怕的,糟糕的', 6),
  ('cake', '中文', 'noun', '蛋糕,糕饼', 6),
  ('drink', '中文', 'noun', '饮料', 6),
  ('hungry', '中文', 'adjective', '饥饿的,饿的', 6),
  ('salty', '中文', 'adjective', '咸的,咸味的', 6),
  ('soup', '中文', 'noun', '汤', 6),
  ('bag', '中文', 'noun', '袋子,包,书包', 6),
  ('coffee', '中文', 'noun', '咖啡', 6),
  ('tea', '中文', 'noun', '茶,茶叶', 6),
  ('bread', '中文', 'noun', '面包', 6),
  ('arm', '中文', 'noun', '手臂,胳膊', 6),
  ('blond', '中文', 'adjective', '亚麻色的,金色的,白皙的', 6),
  ('body', '中文', 'noun', '身体,躯体', 6),
  ('fat', '中文', 'adjective', '胖的,肥胖的', 6),
  ('finger', '中文', 'noun', '手指', 6),
  ('foot', '中文', 'noun', '脚', 6),
  ('grey', '中文', 'adjective', '灰的,灰色的', 6),
  ('hand', '中文', 'noun', '手', 6),
  ('happy', '中文', 'adjective', '快乐的', 6),
  ('know', '中文', 'verb', '知道,了解', 6),
  ('leg', '中文', 'noun', '腿,足,小腿', 6),
  ('long', '中文', 'adjective', '长的,远的', 6),
  ('look', '中文', 'verb', '看,注意', 6),
  ('old', '中文', 'adjective', '老的,上了年纪的', 6),
  ('sad', '中文', 'adjective', '伤心', 6),
  ('short', '中文', 'adjective', '矮的', 6),
  ('shoulder', '中文', 'noun', '肩膀,肩部', 6),
  ('size', '中文', 'noun', '大小,规模,尺寸', 6),
  ('slim', '中文', 'adjective', '细长的,狭长的,苗条的', 6),
  ('tall', '中文', 'adjective', '高的', 6),
  ('tattoo', '中文', 'noun', '纹身', 6),
  ('thin', '中文', 'adjective', '瘦的,肉少的', 6),
  ('tired', '中文', 'adjective', '疲劳的', 6),
  ('toe', '中文', 'noun', '脚趾', 6),
  ('young', '中文', 'adjective', '年轻的,幼小的,新诞生的,新成立的', 6),
  ('chicken', '中文', 'noun', '鸡', 6),
  ('cheese', '中文', 'noun', '奶酪', 6),
  ('dessert', '中文', 'noun', '甜点', 6),
  ('ice cream', '中文', 'noun', '冰激凌', 6),
  ('pizza', '中文', 'noun', '披萨', 6),
  ('rice', '中文', 'noun', '稻,米', 6),
  ('salad', '中文', 'noun', '沙拉,色拉', 6),
  ('apple', '中文', 'noun', '苹果', 6),
  ('milk', '中文', 'noun', '乳,牛奶', 6),
  ('tomato', '中文', 'noun', '番茄,西红柿', 6),
  ('chocolate', '中文', 'noun', '巧克力', 6),
  ('pasta', '中文', 'noun', '意大利面,通心粉', 6),
  ('sandwich', '中文', 'noun', '三明治', 6),
  ('spicy', '中文', 'adjective', '辛辣的,香的', 6),
  ('favorite', '中文', 'noun', '偏爱的人或事物', 7),
  ('housewife', '中文', 'noun', '家庭主妇', 7),
  ('in the morning', '中文', NULL, '在早晨; 明天上午', 7),
  ('police station', '中文', 'noun', '派出所,警察局', 7),
  ('Saturday', '中文', 'noun', '星期六,周六', 7),
  ('Tuesday', '中文', 'noun', '星期二,周二', 7),
  ('Wednesday', '中文', 'noun', '星期三,周三', 7),
  ('Friday', '中文', 'noun', '星期五', 7),
  ('get up', '中文', NULL, '站起; 起来', 7),
  ('a.m.', '中文', 'abbreviation', '上午', 7),
  ('afternoon', '中文', 'noun', '下午', 7),
  ('apartment', '中文', 'noun', '公寓', 7),
  ('check', '中文', 'verb', '检查,核对', 7),
  ('evening', '中文', 'noun', '晚上', 7),
  ('excuse me', '中文', NULL, '劳驾,不好意思(用于请求重复)', 7),
  ('late', '中文', 'adjective', '晚的,迟到的', 7),
  ('meeting', '中文', 'noun', '会议,集会', 7),
  ('midnight', '中文', 'noun', '午夜,子夜', 7),
  ('morning', '中文', 'noun', '早晨,上午', 7),
  ('noon', '中文', 'noun', '正午,中午', 7),
  ('o clock', '中文', 'adverb', '点钟', 7),
  ('p.m.', '中文', 'abbreviation', '下午', 7),
  ('study', '中文', 'verb', '学习', 7),
  ('time', '中文', 'noun', '时间', 7),
  ('internet', '中文', 'noun', '因特网', 7),
  ('ride', '中文', 'verb', '骑', 7),
  ('sleep', '中文', 'verb', '睡觉', 7),
  ('surf', '中文', 'verb', '冲浪', 7),
  ('tennis', '中文', 'noun', '网球', 7),
  ('Thursday', '中文', 'noun', '星期四,周四', 7),
  ('weekend', '中文', 'noun', '周末', 7),
  ('company', '中文', 'noun', '公司,企业', 7),
  ('April', '中文', 'noun', '四月', 7),
  ('August', '中文', 'noun', '八月', 7),
  ('birthday', '中文', 'noun', '生日', 7),
  ('computer game', '中文', 'noun', '电脑游戏', 7),
  ('dance', '中文', 'noun', '跳舞,舞蹈', 7),
  ('December', '中文', 'noun', '十二月', 7),
  ('February', '中文', 'noun', '二月', 7),
  ('go out', '中文', NULL, '外出', 7),
  ('January', '中文', 'noun', '一月', 7),
  ('July', '中文', 'noun', '七月', 7),
  ('June', '中文', 'noun', '六月', 7),
  ('March', '中文', 'noun', '三月', 7),
  ('May', '中文', 'noun', '五月', 7),
  ('movie', '中文', 'noun', '电影', 7),
  ('November', '中文', 'noun', '十一月', 7),
  ('October', '中文', 'noun', '十月', 7),
  ('September', '中文', 'noun', '九月', 7),
  ('sing', '中文', 'verb', '唱歌', 7),
  ('Monday', '中文', 'noun', '星期一', 7),
  ('Sunday', '中文', 'noun', '星期日,周日,礼拜天', 7),
  ('celebrate', '中文', 'verb', '庆祝,祝贺', 8),
  ('invite', '中文', 'verb', '邀请,请求', 8),
  ('never', '中文', 'adverb', '从未,永不,决不', 8),
  ('present', '中文', 'noun', '礼物', 8),
  ('cold', '中文', 'adjective', '寒冷的,冷的', 8),
  ('cool', '中文', 'adjective', '清凉的,凉爽的,凉快的', 8),
  ('degree', '中文', 'noun', '度', 8),
  ('fog', '中文', 'noun', '雾', 8),
  ('foggy', '中文', 'adjective', '模糊的,有雾的', 8),
  ('hot', '中文', 'adjective', '热的', 8),
  ('minus', '中文', 'preposition', '减,减去', 8),
  ('rain', '中文', 'noun', '雨', 8),
  ('rainy', '中文', 'adjective', '下雨的,含雨的,带雨的,多雨的', 8),
  ('snow', '中文', 'noun', '雪', 8),
  ('snowy', '中文', 'adjective', '被大雪覆盖的', 8),
  ('sun', '中文', 'noun', '太阳', 8),
  ('sunny', '中文', 'adjective', '阳光充足的,晴朗的,明媚的', 8),
  ('warm', '中文', 'adjective', '暖和的,温暖的,暖的', 8),
  ('weather', '中文', 'noun', '天气,气候,气象', 8),
  ('wind', '中文', 'noun', '风,气流', 8),
  ('windy', '中文', 'adjective', '多风的,坏天气的,风强的', 8),
  ('dislike', '中文', 'verb', '不喜欢,讨厌', 8),
  ('fall', '中文', 'noun', '秋天,秋季', 8),
  ('hate', '中文', 'verb', '讨厌', 8),
  ('spring', '中文', 'noun', '春天,春季', 8),
  ('summer', '中文', 'noun', '夏天,夏季', 8),
  ('winter', '中文', 'noun', '冬季,冬天', 8),
  ('eat out', '中文', NULL, '在饭馆等处吃饭(不在家中吃)', 8),
  ('TV', '中文', 'noun', '电视机,电视', 8),
  ('watch', '中文', 'verb', '观看,注视', 8),
  ('holiday', '中文', 'noun', '假期', 8),
  ('should', '中文', 'modal verb', '应该,应当', 8),
  ('vacation', '中文', 'noun', '假期,休假', 8),
  ('always', '中文', 'adverb', '总是,永远', 8),
  ('camera', '中文', 'noun', '照相机', 8),
  ('card', '中文', 'noun', '明信片', 8),
  ('party', '中文', 'noun', '政党', 8),
  ('perfume', '中文', 'noun', '香水', 8),
  ('usually', '中文', 'adverb', '经常,通常', 8),
  ('cloud', '中文', 'noun', '云', 8),
  ('cloudy', '中文', 'adjective', '多云的,阴天的,愁容满面的', 8),
  ('sometimes', '中文', 'adverb', '有时,往往,时常', 8);
